


export const  GET_BOOKS_REQUEST=" GET_BOOKS_REQUEST"
export const GET_BOOKS_SUCCESS="GET_BOOKS_SUCCESS"
export const GET_BOOKS_FAILURE = "GET_BOOKS_FAILURE"



export const UPDATE_BOOKS_REQUEST=  "UPDATE_BOOKS_REQUEST"
export const UPDATE_BOOKS_SUCCESS=  "UPDATE_BOOKS_SUCCESS"
export const UPDATE_BOOKS_FAILURE = "UPDATE_BOOKS_FAILURE"